name: Azure Web App CI/CD for Next.js (SSR)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Next.js to Azure Web App

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm ci

      # 4️⃣ Build Next.js
      - name: Build Next.js
        working-directory: ./frontend
        run: |
          npm run build

      # 5️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_AZURE_WEB_APP_NAME        # replace with your Azure Web App name
          slot-name: Production                     # or staging if you use a slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./frontend                       # deploy the frontend folder containing package.json and .next
