name: Deploy Next.js to Azure Web App - trendikala-testing-frontend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write       
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Next.js app
        working-directory: ./frontend
        run: npm run build

      - name: Azure Login (OIDC - No Secrets Needed)
        uses: azure/login@v2
        with:
          enable-AzPSSession: true   # ✅ Works with Deployment Center OIDC Connection

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trendikala-testing-frontend-prod'
          slot-name: 'Production'
          package: ./frontend
