name: Build and deploy Next.js app to Azure Web App - trendikala-testing-frontend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Next.js generally works best with 18.x

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Next.js app
        working-directory: ./frontend
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_17742CF0ACB648FFA3198FA0EB274D82 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73813C7A7B204A00A99017AA9C0A9F03 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CDBA30532EDA4BD6AF9F6C8FD01132B5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trendikala-testing-frontend-prod'
          slot-name: 'Production'
          package: ./frontend    # deploy the whole frontend folder with .next inside
