name: Deploy Backend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3️⃣ Install dependencies & build backend
      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./backend

      - name: Build Backend (optional)
        run: npm run build --if-present
        working-directory: ./backend

      # 4️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID_BACKEND }}
          tenant-id: ${{ secrets.AZURE_TENANTID_BACKEND }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID_BACKEND }}

      # 5️⃣ Deploy backend
      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trendikala-testing-backend'
          package: ./backend
