name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3️⃣ Install dependencies & build
      - name: Install & Build Frontend
        run: |
          npm install
          npm run build
        working-directory: ./frontend

      # 4️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENTID_FRONTEND }}
          tenant-id: ${{ secrets.AZURE_TENANTID_FRONTEND }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID_FRONTEND }}

      # 5️⃣ Deploy frontend
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trendikala-testing-frontend'
          package: ./frontend
