# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Next.js app to Azure Web App - Next-trendikala-testing-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./frontend  # ✅ Upload the built frontend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Required for OIDC login
      contents: read   # Required to download artifacts

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./node-app  # ✅ Download into this folder

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88760890DDD647FEA43A73B77D9629A0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_27219D313271416AB4DE6F060B868A76 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9AED743E65EC438593D4CCEC283F205F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Next-trendikala-testing-prod'
          slot-name: 'Production'
          package: ./node-app  # ✅ Point to the folder where artifact was downloaded
