name: Deploy Backend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./backend

      # Optional: Build backend if needed
      - name: Build Backend
        run: npm run build --if-present
        working-directory: ./backend

      # Deploy to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BACKEND }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BACKEND }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BACKEND }}

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trendikala-testing-backend'
          package: ./backend
