name: Build and deploy Next.js Frontend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3️⃣ Install dependencies & build frontend
      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # 4️⃣ Upload build artifacts (include .next, node_modules, package.json)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: |
            ./frontend/.next
            ./frontend/package.json
            ./frontend/node_modules
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Download build artifacts
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
          path: ./frontend

      # 2️⃣ Login to Azure using Service Principal
      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B9824638481498F8BB3FC758A74A84E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C937C217D60464FB5AE3B1EBBFECA2B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2775CF7B46DB4B1B92EFAC010F7146B3 }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NEXT-trendikala-testing-frontend'
          slot-name: 'Production'
          package: ./frontend

      # 4️⃣ Set Startup Command for Next.js (ensure the app runs correctly)
      - name: Configure Startup Command
        uses: azure/cli@v1
        with:
          azcliversion: 2.57.0
          inlineScript: |
            az webapp config set \
              --name NEXT-trendikala-testing-frontend \
              --resource-group next-trendikala-testing-frontend_group \
              --startup-file "npx next start -p 8080"
