name: Build and deploy Next.js Frontend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies & build
      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build

      # Upload entire frontend folder for deployment
      - name: Upload frontend folder
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Download frontend folder
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B9824638481498F8BB3FC758A74A84E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C937C217D60464FB5AE3B1EBBFECA2B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2775CF7B46DB4B1B92EFAC010F7146B3 }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NEXT-trendikala-testing-frontend'
          slot-name: 'Production'
          package: ./frontend
