name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # 4️⃣ Build Next.js app
      - name: Build Next.js
        run: npm run build
        working-directory: ./frontend

      # 5️⃣ Optional: Export static HTML (agar static hosting chahiye)
      # - name: Export Next.js (optional)
      #   run: npm run export
      #   working-directory: ./frontend

      # 6️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D8BC80652FD54553983E6A134156DF97 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F31E82DFA3E94911B0159B95A2C8107D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A7D06D0873AD436087FE1D96CEE5 }}

      # 7️⃣ Deploy to Azure Web App
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trendikala-testing-frontend'
          package: ./frontend/.next   # Next.js build folder
