# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Next.js frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: ./frontend

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
                ./frontend/.next
                ./frontend/package.json
                ./frontend/package-lock.json
                ./frontend/next.config.js
          
      - name: Upload package.json and next.config.js
        uses: actions/upload-artifact@v4
        with:
          name: config-files
          path: |
            ./frontend/package.json
            ./frontend/next.config.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./node-app

      - name: Download config files
        uses: actions/download-artifact@v4
        with:
          name: config-files
          path: ./deploy-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4736D8F1E1B54AC8AE2193F4E82A2709 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CBA3266525CE4875BCFD573FF69EDF57 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_888CB27E6AD34471AF58E6BD741F1B02 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Next-trendikala-testing-prod'
          slot-name: 'Production'
          package: ./node-app   # Deploy folder with .next + package.json + next.config.js



