name: Build and deploy Next.js to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          cd frontend
          npm install
          npm run build
          
          cp -R .next/standalone/* .
        shell: bash
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8EC6E1A812B34A108FF2BD73B83DE727 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_77654019C84E40548CD99FB54BFAB200 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2675774800504096B16B8EE67F0C26F4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Next-trendikala-testing-prod'
          slot-name: 'Production'
          package: ./frontend/.next/standalone
